baseURL: "http://stannomarjones.com"
languageCode: en-us
title: theplaybook
theme: PaperMod

enableEmoji: true

params:
  author: Stann-Omar Jones
  homeInfoParams:
    Title: "the data playbook"
    Content: >
      Welcome to the **data playbook** 🎉

      - This is a space dedicated to showcasing my data analysis projects. 🙂

  socialIcons:
    - name: Github
      url: "https://github.com/k10sj02"
    - name: Linkedin
      url: "https://www.linkedin.com/in/stannomarjones"
    - name: Rss
      url: "index.xml"

  ShowReadingTime: true
  ShowShareButtons: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
