baseURL: "http://stannomarjones.com"
languageCode: en-us
title: theplaybook
theme: PaperMod

enableEmoji: true

googleAnalytics: # enter code
privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
        
params:
  googleTagManager: "GTM-T842RMZR"
  author: Stann-Omar Jones
  homeInfoParams:
    Title: "Stann-Omar Jones"
    Content: >
      Welcome to the **data playbook** 🎉

      - This is a space dedicated to micro-blogging about topics that interest me and showcasing my data analysis projects. 🙂

  socialIcons:
    - name: github
      url: "https://github.com/k10sj02"
    - name: linkedin
      url: "https://www.linkedin.com/in/stannomarjones"
    - name: rss
      url: "index.xml"

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["twitter", "linkedin", "facebook", "whatsapp", "telegram"]

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: blog
      name: blog
      url: /posts/
      weight: 20
    - identifier: archives
      name: archives
      url: /archives/
      weight: 30
    - identifier: projects
      name: projects
      url: /projects/
      weight: 40
    - identifier: search
      name: search
      url: /search/
      weight: 50
